menu/urls.py
# menu/urls.py
from django.urls import path
from .views import *
app_name = 'menu'

urlpatterns = [
    # path per la lista dei piatti
    path('', MenuListView.as_view(), name='menu'),
    
    # path per operazioni CRUD sui piatti
    path('new_dish/', DishCreateView.as_view(), name='dish_create'),
    path('edit_dish/<pk>', DishUpdateView.as_view(), name='dish_edit'),
    path('delete_dish/<pk>', DishDeleteView.as_view(), name='dish_delete'),
    path('detail_dish/<pk>', DishDetailView.as_view(), name='dish_detail'),
    
    # path per la lista degli ingredienti
    path('ingredient_list/', IngredientListView.as_view(), name='ingredient_list'),
    
    # path per operazioni CRUD sugli ingredienti
    path('new_ingredient/', IngredientCreateView.as_view(), name='ingredient_create'),
    path('edit_ingredient/<pk>', IngredientUpdateView.as_view(), name='ingredient_edit'),
    path('delete_ingredient/<pk>', IngredientDeleteView.as_view(), name='ingredient_delete'),
    path('detail_ingredient/<pk>', IngredientDetailView.as_view(), name='ingredient_detail'),
    
    # path per eseeguire una ricerca
    path ('search/', dish_search, name='dish_search'),
    path ('search_results/', SearchResultsList.as_view(), name='search_results'),
    
    path('dish/<int:dish_id>/', dish_statistics, name='dish_statistics'),


]

orders/urls.py
from django.urls import path
from .views import *
app_name = 'orders'

urlpatterns = [
    path('current/', CurrentOrderDetailView.as_view(), name='current_order_detail'),
    path('current/<int:table_id>/', CurrentOrderDetailView.as_view(), name='current_order_detail_with_id'),
    
    path('delete_order/<int:table_id>/', CurrentOrderDeleteView.as_view(), name='current_order_delete'),
    
    path('update/<int:pk>/', OrderUpdateView.as_view(), name='order_detail_update'),
    path('delete/<int:pk>/', OrderDeleteView.as_view(), name='order_detail_delete'),
    
    path('confirm/', confirm_order_view, name='confirm_order'),
    path('conclude_evening/', conclude_evening_view, name='conclude_evening'),
    path('confirm/<int:table_id>/', confirm_order_view, name='confirm_order_with_id'),
    path('conclude_evening/<int:table_id>/', conclude_evening_view, name='conclude_evening_with_id'),

    path('update_order_detail_status/<int:order_detail_id>/', update_order_detail_status, name='update_order_detail_status'),
    
    path('recommendations/<int:pk>/', order_recommendations_view, name='order_recommendations'),

    path('statistics/', orders_statistics, name='statistics'),



]

sushi/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import *
# from .initcmds import erase_dish_db, erase_ingredient_db, init_ingredient_db, init_dish_db
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static
from orders.reccomendation import create_similarity_matrix, populate_initial_cooccurrence_matrix


urlpatterns = [
    path('', include('restaurant.urls')),  
    
    path('admin/', admin.site.urls, name='admin'),
    
    path("login/", auth_views.LoginView.as_view(), name="login"),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
    path("register/", TableCreateView.as_view(), name="register"),
    path("register_chef/",ChefCreateView.as_view(), name="register_chef"),
    
    path('menu/', include('menu.urls')),

    path('tables/', include('tables.urls')),
    
    path('orders/', include('orders.urls')),
    
]
create_similarity_matrix()
populate_initial_cooccurrence_matrix()
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orders/models.py
from django.db import models
from django.core.exceptions import ValidationError
from tables.models import Table
from menu.models import Dish

class Order(models.Model):
    table = models.ForeignKey(Table, on_delete=models.SET_NULL, null=True)
    order_datetime = models.DateTimeField(auto_now_add=True)
    status = models.CharField(max_length=20, choices=[('da confermare', 'Da confermare'),('confermato', 'Confermato')], default='da confermare')
 
    def __str__(self):
        if self.table is None:
            return f'Ordine {self.id}'
        return f'Ordine {self.id} per il tavolo {self.table.table_number}'


    @property
    def total_price(self):
        return sum(detail.total_price for detail in self.order_details.all())


def validate_positive_nonzero(value):
    if value <= 0:
        raise ValidationError(
            '%(value)s non è un valore valido. La quantità deve essere maggiore di zero.',
            params={'value': value},
        )

class OrderDetail(models.Model):
    STATUS_CHOICES = [
        ('In attesa', 'In attesa'),
        ('In preparazione', 'In preparazione'),
        ('Pronto', 'Pronto')
    ]
    order = models.ForeignKey(Order, on_delete=models.CASCADE, related_name='order_details')
    dish = models.ForeignKey(Dish, on_delete=models.CASCADE)    
    quantity = models.PositiveIntegerField(default=1, validators=[validate_positive_nonzero])
    status = models.CharField(max_length=20, choices= STATUS_CHOICES , default='In attesa')

    def __str__(self):
        return f'{self.quantity} x {self.dish.name} Stato: {self.status}'
    @property
    def total_price(self):
        return self.dish.price * self.quantity
    @property
    def total_earned(self):
        return self.dish.profit * self.quantity
    @property
    def status_choices(self):
        return self.STATUS_CHOICES
    @property
    def move_to_next_status(self):
        current_index = self.get_status_index(self.status) # Ottiene l'indice dello stato corrente
        next_index = (current_index + 1) % len(self.STATUS_CHOICES)  # Calcola l'indice del prossimo stato
        self.status = self.STATUS_CHOICES[next_index][0]  # Assegna il prossimo stato

    def get_status_index(self, status):
    # con la list comprehension ottengo la lista degli stati, in seguito chiamo il metodo index() per ottenere l'indice dello stato passato come argomento
        return [s[0] for s in self.STATUS_CHOICES].index(status)
    
    
class SimilarityMatrix(models.Model):
    dish1 = models.ForeignKey(Dish, related_name='similarity_dish1', on_delete=models.CASCADE)
    dish2 = models.ForeignKey(Dish, related_name='similarity_dish2', on_delete=models.CASCADE)
    similarity = models.FloatField()
    
class CoOccurrenceMatrix(models.Model):
    dish1 = models.ForeignKey(Dish, related_name='cooccurrence_dish1', on_delete=models.CASCADE)
    dish2 = models.ForeignKey(Dish, related_name='cooccurrence_dish2', on_delete=models.CASCADE)
    count = models.PositiveIntegerField(default=0)

orders/forms.py
from django import forms
from .models import OrderDetail

# class AddDishForm(forms.ModelForm):
#     class Meta:
#         model = OrderDetail
#         fields = ['quantity']

class AddDishForm(forms.ModelForm):
    quantity = forms.IntegerField(
        label="Quantità",
        min_value=1,  # Assicura che il campo del modulo non accetti valori minori di 1
        initial=1,  # Imposta il valore iniziale del campo del modulo a 1
    )

    class Meta:
        model = OrderDetail
        fields = ['quantity']

class ConfirmOrderForm(forms.Form):
    confirm = forms.BooleanField(required=True, label="Conferma ordine")

orders/views.py
from django.views.generic import DetailView, UpdateView, DeleteView, View
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse_lazy 
from .models import Order, OrderDetail
from tables.models import Table
from django.shortcuts import redirect, render
from django.contrib import messages
from django.contrib.auth.decorators import user_passes_test, login_required
from .reccomendation import get_reccomendations, update_cooccurrence_matrix
from django.db.models import Sum

def has_group(user):
    return user.groups.filter(name='Chef').exists()

@user_passes_test(has_group)  
def orders_statistics(request):
    # Filtra gli ordini confermati
    confirmed_orders = Order.objects.filter(status='confermato')

    # Inizializza le variabili per i calcoli
    total_cashed = 0
    total_earned = 0
    total_quantity = 0
    total_order_details = 0

    # Itera sugli ordini confermati per calcolare i totali
    for order in confirmed_orders:
        for order_detail in order.order_details.all():
            total_cashed += order_detail.total_price # Totale incassato
            total_earned += order_detail.total_earned # Totale guadagnato
            total_order_details += 1 # Totale dettagli ordini
            total_quantity += order_detail.quantity # Totale quantità piatti

    # Calcola il numero totale di ordini
    total_orders = confirmed_orders.count()
    
    # Media dettagli ordini per ordine
    
    avg_order_details_per_order = round(total_order_details / total_orders, 2) if total_orders > 0 else 0
    # Media quantità per ordine
    avg_quantity_per_order = round(total_quantity / total_orders, 2) if total_orders > 0 else 0
    
    top_3_dishes = OrderDetail.objects.values('dish__name').annotate(total_ordered=Sum('quantity')).order_by('-total_ordered')[:3]
    bottom_3_dishes = OrderDetail.objects.values('dish__name').annotate(total_ordered=Sum('quantity')).order_by('total_ordered')[:3]

    context = {
        'total_cashed': total_cashed,
        'total_earned': total_earned,
        'total_orders': total_orders,
        'total_quantity': total_quantity,
        'total_order_details': total_order_details, 
        'avg_order_details_per_order': avg_order_details_per_order,
        'avg_quantity_per_order': avg_quantity_per_order,
        'top_3_dishes': top_3_dishes,
        'bottom_3_dishes': bottom_3_dishes,
    }

    return render(request, 'orders/statistics.html', context)

class CurrentOrderDetailView(LoginRequiredMixin, DetailView):
    model = Order
    template_name = 'orders/current_order.html'
    context_object_name = 'order'
    
    def get_object(self):
        # Controlla se table_id è presente nei kwargs
        table_id = self.kwargs.get('table_id')
        if table_id:
            # Ottieni il tavolo dal parametro URL
            table = get_object_or_404(Table, id=table_id)
        else:
            # Ottieni il tavolo dall'utente loggato
            table = self.request.user.table

        try:
            # Cerca un ordine associato al tavolo con stato 'da confermare'
            return Order.objects.get(table=table, status='da confermare')
        except Order.DoesNotExist:
            # Se non esiste un ordine con stato 'da confermare', ritorna None
            return None

class CurrentOrderDeleteView(LoginRequiredMixin, DeleteView):
    model = Order
    template_name = 'orders/current_order_delete.html'
    context_object_name = 'order'
    success_url = reverse_lazy('menu:menu')
    
    def get_object(self, queryset=None):
        table = get_object_or_404(Table, id=self.kwargs['table_id'])
        return get_object_or_404(Order, table=table, status='da confermare')

    #inserire un messaggio di successo col metodo post
    def post(self, request, *args, **kwargs):
        messages.success(request, "Ordine cancellato con successo!!!")
        return super().post(request, *args, **kwargs)    
     
class OrderUpdateView(LoginRequiredMixin, UpdateView):
    model = OrderDetail
    template_name = 'orders/order_detail_update.html'
    fields = ['quantity']
    context_object_name = 'order_detail'
    success_url = reverse_lazy('orders:current_order_detail')
    def form_valid(self, form):
        response = super().form_valid(form)
        messages.success(self.request, 'Aggiornamento dell\'ordine avvenuto con successo!!!')
        return response

class OrderDeleteView(LoginRequiredMixin, DeleteView):
    model = OrderDetail
    template_name = 'orders/order_detail_delete.html'
    context_object_name = 'order_detail'
    success_url = reverse_lazy('orders:current_order_detail')
    def form_valid(self, form):
        response = super().form_valid(form)
        messages.success(self.request, 'Eliminazione dell piatto avvenuta con successo!!!')
        return response

# @deprecated
# class ConfirmOrderView(LoginRequiredMixin, View):
#     def get(self, request, *args, **kwargs):
#         # Controlla se table_id è presente nei kwargs
#         table_id = self.kwargs.get('table_id')
#         if table_id:
#             # Ottieni il tavolo dal parametro URL
#             table = get_object_or_404(Table, id=table_id)
#         else:
#             # Ottieni il tavolo dall'utente loggato
#             table = request.user.table
#         order = get_object_or_404(Order, table=table, status='da confermare')
#         # Cambio lo stato dell'ordine in 'confermato'
#         order.status = 'confermato'
#         order.save()
#         return redirect('menu:menu')
    
@login_required
def confirm_order_view(request, table_id=None):
    if table_id:
        table = get_object_or_404(Table, id=table_id)
    else:
        table = request.user.table

    order = get_object_or_404(Order, table=table, status='da confermare')
    
    if not order.order_details.exists():
        order.delete()
        messages.warning(request, "L'ordine è vuoto, quindi è stato eliminato, nice try ;-)")
        return redirect('tables:table_detail', pk=table.id)

    order.status = 'confermato'
    order.save()
    
    update_cooccurrence_matrix(order)
    
    return redirect('orders:order_recommendations', pk=order.pk)

# @deprecated
# class ConcludeEveningView(LoginRequiredMixin,  View):
#     def post(self, request, *args, **kwargs):
#         # Controlla se table_id è presente nei kwargs
#         table_id = self.kwargs.get('table_id')
#         if table_id:
#             # Ottieni il tavolo dal parametro URL
#             table = get_object_or_404(Table, id=table_id)
#         else:
#             # Ottieni il tavolo dall'utente loggato
#             table = request.user.table
            
#         # Filtra gli ordini associati al tavolo corrente
#         orders = Order.objects.filter(table=table)
#         for order in orders:
#             # Verifica se ci sono ordini non pronti
#             # print(order)
#             # print (order.order_details.all())
#             # print(order.order_details.all().filter(status='In attesa'or 'In preparazione'))
#             if( order.order_details.all().filter(status='In attesa' )):
#                 # Ci sono ordini non pronti, restituisci un messaggio di avviso
#                 print("Mascalzone")
#                 messages.error(request, "Gli ordini devono essere tutti pronti per poter concludere la serata.")
#                 return redirect('tables:table_detail' , pk=table.id)
                
#         # Calcola il totale complessivo degli ordini
#         total_price = sum(order.total_price for order in orders)
#         # Dissocia gli ordini dal tavolo corrente
#         orders.update(table=None)
#         # Reindirizza alla pagina di conferma serata con il totale complessivo
#         return render(request, 'orders/conclude_evening.html', {'total_price': total_price})
    
@login_required
def conclude_evening_view(request, table_id=None):
    if request.method == 'POST':
        if table_id:
            # Ottieni il tavolo dal parametro URL
            table = get_object_or_404(Table, id=table_id)
        else:
            # Ottieni il tavolo dall'utente loggato
            table = request.user.table
            
        # Filtra gli ordini associati al tavolo corrente
        orders = Order.objects.filter(table=table)
        for order in orders:
            # Verifica se ci sono ordini non pronti
            if order.order_details.all().filter(status='In attesa') or order.order_details.all().filter(status='In preparazione') :
                print("Mascalzone")
                # Ci sono ordini non pronti, restituisci un messaggio di avviso
                messages.error(request, "Gli ordini devono essere tutti pronti per poter concludere la serata.")
                return redirect('tables:table_detail', pk=table.id)
                
        # Calcola il totale complessivo degli ordini
        total_price = sum(order.total_price for order in orders)
        # Dissocia gli ordini dal tavolo corrente
        orders.update(table=None)
        # Reindirizza alla pagina di conferma serata con il totale complessivo
        return render(request, 'orders/conclude_evening.html', {'total_price': total_price})
    else:
        # Se il metodo non è POST, reindirizza alla homepage o mostra un messaggio di errore
        messages.error(request, "Richiesta non valida.")
        return redirect('home')

# DEPRECATO
# class UpdateOrderDetailStatus(GroupRequiredMixin, View):
#     group_required = 'Chef'
#     def post(self, request, *args, **kwargs):
#         order_detail_id=self.kwargs['order_detail_id']
#         order_detail=get_object_or_404(OrderDetail, id=order_detail_id)
#         order_detail.move_to_next_status
#         order_detail.save()
#         return redirect('tables:table_detail', order_detail.order.table.id)

from django.http import JsonResponse

@user_passes_test(has_group)  
def update_order_detail_status(request, order_detail_id):

orders/templates/orders/conclude_evening.html
{% extends 'base.html' %}

{% block title %}Serata Conclusa{% endblock %}

{% block content %}
<h1>Serata Conclusa</h1>
<p>Il totale complessivo degli ordini è: {{ total_price }} €</p>
<p>Grazie per aver utilizzato il nostro servizio!</p>
{% endblock %}

orders/templates/orders/current_order.html
{% extends 'base.html' %}

{% block title %}Ordine Corrente{% endblock %}

{% block content %}
    {% if messages %}
    {% for message in messages %}
        <div class="alert alert-{{ message.tags }}" role="alert">
        {{ message }}
        </div>
    {% endfor %}
    {% endif %}
<h1>Ordine Corrente</h1>
<ul>
    {% if order %}
        Ordine {{ order.id }} - {{ order.order_datetime }}
        {% for detail in order.order_details.all %}
            <li>
                {% comment %} Non uso il normale dettaglio perché mostrerebbe lo status e non avrebbe senso {% endcomment %}
                {{ detail.quantity }} x {{ detail.dish.name }}
                <a class="btn btn-primary" href="{% url 'orders:order_detail_update' detail.pk %}">Modifica</a>
                <a class="btn btn-secondary" href="{% url 'orders:order_detail_delete' detail.pk %}">Elimina</a>
                <br><br>
            </li>
        {% endfor %}
        <p>Totale: {{ order.total_price }} €</p>
        <a class="btn btn-success" href="{% url 'orders:confirm_order_with_id' order.table.id %}">Conferma Ordine</a>
        <!-- Form per eliminare l'ordine -->
        <form method="post" action="{% url 'orders:current_order_delete' order.table.id %}" style="display:inline;">
            {% csrf_token %}
            <button class="btn btn-danger" type="submit" onclick="return confirm('Sei sicuro di voler eliminare questo ordine?');">Elimina Ordine</button>
        </form>

    {% else %}
        <p>Nessun ordine da confermare.</p>
    {% endif %}
</ul>

{% endblock %}

orders/templates/orders/current_order_delete.html
{% extends 'base.html' %}

{% block content %}
    <h1>Elimina ordine</h1>
    <p>Sicuro di voler cancellare l'ordine corrente?</p>
    <form method="post">
        {% csrf_token %}
        <button class="btn btn-danger" type="submit">Elimina Ordine</button>
    </form>
{% endblock %}

orders/templates/orders/order_confirm.html
{% extends 'base.html' %}

{% block title %}Conferma Ordine{% endblock %}

{% block content %}
<h1>Conferma Ordine</h1>
<form method="post">
    {% csrf_token %}
    <p>Sei sicuro di voler confermare l'ordine?</p>
    <button type="submit" class="btn btn-success">Conferma</button>
    <a class="btn btn-danger" href="{% url 'menu:menu' %}">Annulla</a>
</form>
{% endblock %}

orders/templates/orders/order_detail_delete.html
{% extends 'base.html' %}

{% block title %}Conferma Eliminazione Dettaglio Ordine{% endblock %}

{% block content %}
<h1>Conferma Eliminazione</h1>
<p>Sei sicuro di voler eliminare {{ order_detail.dish.name }} dall'ordine?</p>
<form method="post">
    {% csrf_token %}
    <button type="submit" class="btn btn-danger">Elimina</button>
    <a class="btn btn-success" href="{% url 'orders:current_order_detail' %}">Annulla</a>
</form>
{% endblock %}

orders/templates/orders/order_detail_update.html
{% extends 'base.html' %}

{% block title %}Modifica Dettaglio Ordine{% endblock %}

{% block content %}
<h1>Modifica Dettaglio Ordine</h1>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-success">Salva</button>
    <a class="btn btn-danger" href="{% url 'orders:current_order_detail' %}">Annulla</a>

</form>
{% endblock %}

orders/templates/orders/order_recommendations.html
{% extends 'base.html' %}

{% block title %}Raccomandazioni{% endblock %}

{% block content %}
<h1>Raccomandazioni in base al tuo ordine</h1>
{% if recommended_dishes %}
    <ul>
        {% for dish in recommended_dishes %}
            <li><a href="{% url 'menu:dish_detail' dish.pk %}">{{ dish.name }}</a></li>
        {% endfor %}
    </ul>
{% else %}
    <p>Non ci sono piatti suggeriti</p>
{% endif %}
{% endblock %}

orders/templates/orders/statistics.html
{% extends 'base.html' %}

{% block title %}Statistiche{% endblock %}

{% block content %}
<h1>Statistiche Generali</h1>
<ul>
    <li>Totale Incassato: {{ total_cashed }} €</li>
    <li>Totale Guadagnato: €{{ total_earned }} €</li>
    <li>Numero Totale di Ordini: {{ total_orders }}</li>
    <li>Numero Totale di dettagli d'ordine: {{ total_order_details }}</li>
    <li>Numero Totale di Piatti Venduti: {{ total_quantity }}</li>
    <li>Quantità Media di dettagli d'ordine per Ordine: {{ avg_order_details_per_order }}</li>
    <li>Quantità Media di Piatti per Ordine: {{ avg_quantity_per_order }}</li>
</ul>

<h2>Top 3 Piatti Più Ordinati</h2>
<ul>
    {% for dish in top_3_dishes %}
        <li>{{ dish.dish__name }}: {{ dish.total_ordered }} volte</li>
    {% endfor %}
</ul>

<h2>Top 3 Piatti Meno Ordinati</h2>
<ul>
    {% for dish in bottom_3_dishes %}
        <li>{{ dish.dish__name }}: {{ dish.total_ordered }} volte</li>
    {% endfor %}
</ul>
</ul>
{% endblock %}