menu/urls.py
# menu/urls.py
from django.urls import path
from .views import *
app_name = 'menu'

urlpatterns = [
    # path per la lista dei piatti
    path('', MenuListView.as_view(), name='menu'),
    
    # path per operazioni CRUD sui piatti
    path('new_dish/', DishCreateView.as_view(), name='dish_create'),
    path('edit_dish/<pk>', DishUpdateView.as_view(), name='dish_edit'),
    path('delete_dish/<pk>', DishDeleteView.as_view(), name='dish_delete'),
    path('detail_dish/<pk>', DishDetailView.as_view(), name='dish_detail'),
    
    # path per la lista degli ingredienti
    path('ingredient_list/', IngredientListView.as_view(), name='ingredient_list'),
    
    # path per operazioni CRUD sugli ingredienti
    path('new_ingredient/', IngredientCreateView.as_view(), name='ingredient_create'),
    path('edit_ingredient/<pk>', IngredientUpdateView.as_view(), name='ingredient_edit'),
    path('delete_ingredient/<pk>', IngredientDeleteView.as_view(), name='ingredient_delete'),
    path('detail_ingredient/<pk>', IngredientDetailView.as_view(), name='ingredient_detail'),
    
    # path per eseeguire una ricerca
    path ('search/', dish_search, name='dish_search'),
    path ('search_results/', SearchResultsList.as_view(), name='search_results'),
    
    path('dish/<int:dish_id>/', dish_statistics, name='dish_statistics'),


]

sushi/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import *
# from .initcmds import erase_dish_db, erase_ingredient_db, init_ingredient_db, init_dish_db
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static
from orders.reccomendation import create_similarity_matrix, populate_initial_cooccurrence_matrix


urlpatterns = [
    path('', include('restaurant.urls')),  
    
    path('admin/', admin.site.urls, name='admin'),
    
    path("login/", auth_views.LoginView.as_view(), name="login"),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
    path("register/", TableCreateView.as_view(), name="register"),
    path("register_chef/",ChefCreateView.as_view(), name="register_chef"),
    
    path('menu/', include('menu.urls')),

    path('tables/', include('tables.urls')),
    
    path('orders/', include('orders.urls')),
    
]
create_similarity_matrix()
populate_initial_cooccurrence_matrix()
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

menu/models.py
from django.db import models
from django.core.validators import MinValueValidator


class Ingredient(models.Model):
    name = models.CharField(max_length=100, unique=True, error_messages={
            'unique': "Nome già esistente!!! Non è possibile avere due ingreidenti con lo stesso nome.",
        })
    
    def __str__(self):
        return self.name

class Dish(models.Model):
    name = models.CharField(max_length=100, unique=True, error_messages={
            'unique': "Nome già esistente!!! Non è possibile avere due piatti con lo stesso nome.",
        })
    description = models.TextField()
    
    price = models.FloatField(blank=False, validators=[MinValueValidator(0.01)])
    ingredients = models.ManyToManyField(Ingredient, related_name='dishes')
    profit = models.FloatField(blank=False, validators=[MinValueValidator(0.01)])
    image = models.ImageField(upload_to='dish_images/', blank=True, null=True)

    def __str__(self):
        return self.name

menu/forms.py
from django import forms
from .models import Ingredient, Dish
from django.core.validators import MinValueValidator
from django.core.exceptions import ValidationError


class DishSearchForm(forms.Form):
    name = forms.CharField(label='Nome del piatto', max_length=100, required=False)
    ingredients = forms.ModelMultipleChoiceField(
        queryset=Ingredient.objects.all(),
        label='Ingredienti',
        required=False,
        widget=forms.CheckboxSelectMultiple
    )
    max_price = forms.DecimalField(label='Prezzo massimo', max_digits=10, decimal_places=2, required=False, min_value=1)

class DishForm(forms.ModelForm):
    class Meta:
        model = Dish
        fields = '__all__'
        widgets = {
            'ingredients': forms.CheckboxSelectMultiple
        }
    price = forms.DecimalField(
        max_digits=10, 
        decimal_places=2, 
        validators=[MinValueValidator(0.01)], 
        label='Prezzo',
        error_messages={
            'min_value': 'Il prezzo deve essere maggiore di 0.01',
        }

    )
    profit = forms.DecimalField(
        max_digits=10, 
        decimal_places=2, 
        validators=[MinValueValidator(0.01)], 
        label='Profitto',
        error_messages={
            'min_value': 'Il profitto deve essere maggiore di 0.01',
        }
    )

menu/views.py
from django.views.generic import ListView, CreateView, UpdateView, DeleteView, DetailView
from .models import *
from orders.models import Order
from tables.models import Table
from .forms import *
from orders.forms import AddDishForm
from django.urls import reverse_lazy
from braces.views import GroupRequiredMixin
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse
from django.contrib import messages
from orders.models import OrderDetail, Order
from django.contrib.auth.decorators import user_passes_test
from orders.reccomendation import create_similarity_matrix

def has_group(user):
    return user.groups.filter(name='Chef').exists()

@user_passes_test(has_group)  
def dish_statistics(request, dish_id):
    dish = get_object_or_404(Dish, id=dish_id)
    # QuerySet che contiene tutti i OrderDetail per il piatto specifico.
    order_details = OrderDetail.objects.filter(dish=dish)

    total_cashed = 0
    total_earned = 0
    total_quantity = 0
    
    for detail in order_details:
        total_cashed += detail.total_price
        total_earned += detail.quantity * detail.dish.profit
        total_quantity += detail.quantity


    # .values('order'): Estrae i valori del campo order da ciascun OrderDetail nel QuerySet., .distinct(): Filtra i risultati per mantenere solo i valori distinti. 
    #  count(): Conta il numero di risultati distinti.
    total_orders = order_details.values('order').distinct().count() # Numero di ordini distinti in cui il piatto è presente.
    
    context = {
        'dish': dish,
        'total_cashed': total_cashed, # Totale incassato per il piatto
        'total_earned': total_earned,
        'total_orders': total_orders,
        'total_quantity': total_quantity,
    }

    return render(request, 'menu/dish_statistics.html', context)

def dish_search(request):
    if request.method == "POST":
        form = DishSearchForm(request.POST)
        if form.is_valid():
            name = form.cleaned_data.get('name')
            ingredients = form.cleaned_data.get('ingredients')
            max_price = form.cleaned_data.get('max_price')
            ingredient_ids = ','.join(str(ingredient.id) for ingredient in ingredients)
            query_params = {
                'name': name or "",
                'ingredients': ingredient_ids or "",
                'max_price': max_price or "",
            }
            print(query_params)
            query_string = '&'.join([f'{key}={value}' for key, value in query_params.items() if value])
            return redirect(f"{reverse('menu:search_results')}?{query_string}")

    else:
        form = DishSearchForm()  
    return render(request,template_name="menu/search_dish.html",context={"form":form})

class SearchResultsList(ListView):
    model = Dish
    template_name = "menu/search_results.html"
    
    def get_queryset(self):
        name = self.request.GET.get('name')
        ingredients = self.request.GET.get("ingredients")
        max_price = self.request.GET.get("max_price")

        if (name or ingredients or max_price):
            dishes= Dish.objects.all()
            if name:
                dishes = dishes & Dish.objects.filter(name__icontains=name) 
            if ingredients:
                ingredient_ids = [int(id) for id in ingredients.split(',') if id]
                for ingredient_id in ingredient_ids:
                    dishes = dishes & Dish.objects.filter(ingredients=ingredient_id)        
            if max_price:
                dishes = dishes & Dish.objects.filter(price__lte=max_price)
            print(dishes)
            return dishes
        else:
            return Dish.objects.none()
   
# View per la lista dei piatti
class MenuListView(ListView):
    model = Dish
    template_name = 'menu/menu.html'
    context_object_name = 'menu'
    #restituire i piatti in ordine alfabetico
    def get_queryset(self):
        return Dish.objects.all().order_by('name')
    
 
# Views per i piatti   
class DishCreateView(GroupRequiredMixin, CreateView):
    group_required = ["Chef"]
    model = Dish
    template_name = 'menu/dish_create.html'
    form_class = DishForm
    success_url = reverse_lazy('menu:menu')
    def form_valid(self, form):
        response = super().form_valid(form)
        messages.success(self.request, 'Creazione del piatto avvenuta con successo!!!')
        create_similarity_matrix()
        return response

     
class DishUpdateView(GroupRequiredMixin, UpdateView):
    group_required = ["Chef"]
    model = Dish
    template_name = 'menu/dish_update.html'
    form_class = DishForm
    success_url = reverse_lazy('menu:menu')
    def form_valid(self, form):
        response = super().form_valid(form)
        messages.success(self.request, 'Aggiornamento del piatto avvenuto con successo!!!')
        create_similarity_matrix()
        return response
       
class DishDeleteView(GroupRequiredMixin, DeleteView):
    group_required = ["Chef"]
    model = Dish
    template_name = 'menu/dish_delete.html'
    success_url = reverse_lazy('menu:menu')
    
    def post(self, request, *args, **kwargs):
        messages.success(self.request, "Eliminazione del piatto avvenuta con successo!!!")
        create_similarity_matrix()
        return super().delete(request, *args, **kwargs)


class DishDetailView(DetailView):
    model = Dish
    template_name = 'menu/dish_detail.html'
    context_object_name = 'dish'
    # Essendo un detail view non ha una form per aggiungere un piatto all'ordine, quindi bisogna creare un form apposito e aggiungerlo
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = AddDishForm()
        return context

    # Tutto questo casino serbe per aggiungere un piatto all'ordine
    def post(self, request, *args, **kwargs):
        # Recupera il piatto che l'utente sta visualizzando.
        self.object = self.get_object()

        # Crea un'istanza del form `AddDishForm` con i dati POST.
        form = AddDishForm(request.POST)

        if form.is_valid():
            # Recupera l'utente corrente e il tavolo associato.
            user = request.user
            table = get_object_or_404(Table, user=user)
            
            # Cerca un ordine esistente per il tavolo con lo stato 'da confermare' o ne crea uno nuovo se non esiste.
            order, created= Order.objects.get_or_create(table=table, status='da confermare')
            # Creo l'order_detail con la quantità presa dal form, il piatto ottenuto precedentemente e l'ordine ottenuto precedentemente
            
            order_detail = form.save(commit=False)
            order_detail.order = order
            order_detail.dish = self.object
            
            # Salvataggio
            order_detail.save()
            # Aggiungi un messaggio di successo
            messages.success(request, 'Piatto aggiunto all\'ordine con successo!')

            # Reindirizza l'utente alla vista del dettaglio dell'ordine appena creato o aggiornato.        
            return redirect('menu:menu')

        # se il form non è valido, renderizza di nuovo la pagina con il form
        return self.render_to_response(self.get_context_data(form=form))
    
# Views per gli ingredienti
class IngredientListView(ListView):
    model = Ingredient
    template_name = 'menu/ingredient_list.html'
    context_object_name = 'ingredients'
 
class IngredientCreateView(GroupRequiredMixin, CreateView):
    group_required = ["Chef"]
    model = Ingredient
    template_name = 'menu/ingredient_create.html'
    fields = '__all__'
    success_url = reverse_lazy('menu:ingredient_list')
    def form_valid(self, form):
        response = super().form_valid(form)
        messages.success(self.request, 'Creazione dell\'ingrediente avvenuta con successo!!!')
        return response

class IngredientUpdateView(GroupRequiredMixin, UpdateView):
    group_required = ["Chef"]
    model = Ingredient
    template_name = 'menu/ingredient_update.html'
    fields = '__all__'
    success_url = reverse_lazy('menu:ingredient_list')
    def form_valid(self, form):
        response = super().form_valid(form)
        messages.success(self.request, 'Aggiornamento dell\'ingrediente avvenuto con successo!!!')
        return response

class IngredientDeleteView(GroupRequiredMixin, DeleteView):
    group_required = ["Chef"]
    model = Ingredient
    template_name = 'menu/ingredient_delete.html'
    success_url = reverse_lazy('menu:ingredient_list')
    def post(self, request, *args, **kwargs):
        messages.success(self.request, "Eliminazione dell'ingrediente avvenuta con successo!!!")
        return super().delete(request, *args, **kwargs)

class IngredientDetailView(DetailView):
    model = Ingredient
    template_name = 'menu/ingredient_detail.html'
    context_object_name = 'ingredient'

menu/templates/menu/dish_create.html
{% extends 'base.html' %}

{% block title %} Crea Piatto {% endblock %} 

{% block content %}
    <h1> Crea Piatto </h1>
    <form method="post" enctype="multipart/form-data">{% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-success">Crea</button>
    </form>

{% endblock %}

menu/templates/menu/dish_delete.html
{% extends 'base.html' %}

{% block title %}Elimina {{ dish.name}}{% endblock %}


{% block content %}
    <h1>Elimina piatto</h1>
    <p>Sei sicuro di voler eliminare questo piatto: "{{ dish.name }}"?</p>
    <form method="post">
        {% csrf_token %}
        <div class="d-flex ">
            <button type="submit" class="btn btn-danger mr-2">Elimina</button>
            <a class="btn btn-info" href="{% url 'menu:dish_detail' dish.pk %}">Torna al dettaglio del piatto</a>
        </div>
    </form>
{% endblock %}

menu/templates/menu/dish_detail.html
{% extends 'base.html' %}

{% block title %}{{ dish.name}}{% endblock %}

{% block content %}
    <h1>{{ dish.name }}</h1>
    <br>
    <p>{{ dish.description }}</p>
    <br>
    {% if dish.image %}
        <img src="{{ dish.image.url }}" alt="{{ dish.name }}" width="300" height="300">
    {% else %}
        <p>Nessuna immagine disponibile.</p>
    {% endif %}
    <br>
    <p>Prezzo:{{ dish.price }} €</p>
    <p>Ingredienti:</p>
    <ul>
        {% for ingredient in dish.ingredients.all %}
            <li>{{ ingredient }}</li>
        {% endfor %}
    </ul>
    {% if user.is_authenticated and "Tavolo" in user.groups.all.0.name %}
    <form method="post" action="">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-success">Aggiungi all'ordine</button>
    </form>
{% endif %}

    {% if user.is_authenticated and "Chef" in user.groups.all.0.name  %}
        <a class="btn btn-info" href="{% url 'menu:dish_statistics' dish.pk %}">Statistiche</a> <!-- Tasto per visualizzare le statistiche del piatto -->
        <a class="btn btn-success" href="{% url 'menu:dish_edit' dish.pk %}">Modifica</a> <!-- Tasto per modificare il piatto -->
        <a class="btn btn-danger" href="{% url 'menu:dish_delete' dish.pk %}">Elimina</a> <!-- Tasto per eliminare il piatto -->
    {% endif %}

{% endblock %}

menu/templates/menu/dish_statistics.html
{% extends 'base.html' %}

{% block title %}Statistiche del Piatto {% endblock %}

{% block content %}
<h1>Statistiche per {{ dish.name }}</h1>
{{dish.name}} 
<p>Prezzo:{{ dish.price }} €</p>
<p>Profitto: {{dish.profit}} €</p>
<p>Ingredienti:</p>
    <ul>
        {% for ingredient in dish.ingredients.all %}
            <li>{{ ingredient }}</li>
        {% endfor %}
    </ul>
<h3>Statistiche:</h3>
<ul>
    <li>Totale Incassato: {{ total_cashed }}€</li>
    <li>Totale Guadanato: {{ total_earned }}€</li>
    <li>Numero di Ordini in cui {{dish.name}} compare: {{ total_orders }}</li>
    <li>Quantità totale ordinata: {{ total_quantity }}</li>
</ul>
{% endblock %}

menu/templates/menu/dish_update.html
{% extends 'base.html' %}

{% block title %}Modifica {{dish.name}}{% endblock %}

{% block content %}
    <h1>Modifica Piatto</h1>
    <div class="d-flex justify-content-between">
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <div class="d-flex ">
            <button type="submit" class="btn btn-success mr-2">Conferma</button>
            <a class="btn btn-info" href="{% url 'menu:dish_detail' dish.pk %}">Torna al dettaglio del piatto</a>
        </div>
    </form>
        {% endblock %}

menu/templates/menu/ingredient_create.html
{% extends 'base.html' %}

{% block title %} Aggiungi Ingrediente {% endblock %} 

{% block content %}
    <h1> Aggiungi Ingrediente </h1>
    <form method="post">{% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-success">Crea</button>
    </form>

{% endblock %}

menu/templates/menu/ingredient_delete.html
{% extends 'base.html' %}

{% block title %}Elimina {{ ingredient.name}}{% endblock %}


{% block content %}
    <h1>Elimina Ingrediente</h1>
    <p>Sei sicuro di voler eliminare questo ingrediente: "{{ ingredient.name }}"?</p>
    <form method="post">
        {% csrf_token %}
        <div class="d-flex ">
            <button type="submit" class="btn btn-danger mr-2">Elimina</button>
            <a class="btn btn-info" href="{% url 'menu:ingredient_detail' ingredient.pk %}">Torna al dettaglio dell'ingrediente</a>
        </div>
    </form>
{% endblock %}

menu/templates/menu/ingredient_detail.html
{% extends 'base.html' %}

{% block title %}{{ ingredient.name}}{% endblock %}


{% block content %}
    <h1>{{ ingredient.name }}</h1>
    <br>
    {% if user.is_authenticated and "Chef" in user.groups.all.0.name  or user.is_staff %}
        <a class="btn btn-success" href="{% url 'menu:ingredient_edit' ingredient.pk %}">Modifica</a> <!-- Tasto per modificare il piatto -->
        <a class="btn btn-danger" href="{% url 'menu:ingredient_delete' ingredient.pk %}">Elimina</a> <!-- Tasto per eliminare il piatto -->
    {% endif %}

{% endblock %}

menu/templates/menu/ingredient_list.html
{% extends 'base.html' %}


{% block title %}Restaurant Ingredients{% endblock %}

{% block content %}
    {% if messages %}
      {% for message in messages %}
        <div class="alert alert-{{ message.tags }}" role="alert">
          {{ message }}
        </div>
      {% endfor %}
    {% endif %}
    <h1>Ingredienti</h1>
    {% if ingredients %}
    <ul class="list-group list-group-flush">
        {% for ingredient in ingredients %}
        <li class="list-group-item"><a href="{% url 'menu:ingredient_detail' ingredient.pk %}">{{ ingredient }}</a></li>
        {% endfor %}
    </ul>
    {% else %}
        <p>Non ci sono ingredienti.</p>
    {% endif %}

    {% if user.is_authenticated and "Chef" in user.groups.all.0.name%}
        <a class="btn btn-success" href="{% url 'menu:ingredient_create' %}">Aggiungi un nuovo ingrediente</a> <!-- Tasto per aggiungere un nuovo ingrediente -->
    {% endif %}

{% endblock %}

menu/templates/menu/ingredient_update.html
{% extends 'base.html' %}

{% block title %}Modifica {{ingredient.name}}{% endblock %}

{% block content %}
    <h1>Modifica Ingrediente</h1>
    <form method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <div class="d-flex ">
            <button type="submit" class="btn btn-success mr-2">Conferma</button>
            <a class="btn btn-info" href="{% url 'menu:ingredient_detail' ingredient.pk %}">Torna al dettaglio dell'ingrediente</a>
        </div>
    </form>
    </form>
{% endblock %}

menu/templates/menu/menu.html
{% extends 'base.html' %}


{% block title %}Restaurant Menu{% endblock %}

{% block content %}
{% if messages %}
    {% for message in messages %}
        <div class="alert alert-{{ message.tags }}" role="alert">
            {{ message }}
        </div>
    {% endfor %}
{% endif %}
<h1 class="text-center my-4">Menu</h1>
<div class="container">
      <div class="row">
          {% if menu %}
              {% for dish in menu %}
              <div class="col-md-4">
                  <div class="card mb-4" style="width: 18rem;">
                      {% if dish.image %}
                      <img src="{{ dish.image.url }}" class="card-img-top" alt="...">
                      {% endif %}
                      <div class="card-body">
                        <h5 class="card-title">{{dish.name}}</h5>
                        <p class="card-text">{{dish.description}}</p>
                        <a href="{% url 'menu:dish_detail' dish.pk %}" class="btn btn-primary">Dettaglio</a>
                      </div>
                  </div>
              </div>
              {% endfor %}
          {% else %}
              <div class="col-12">
                  <p>Non ci sono piatti disponibili.</p>
              </div>
          {% endif %}
      </div>
  </div>
  
    <div>
    <a class="btn btn-primary d-inline" href="{% url 'menu:dish_search' %}">Ricerca</a> <!-- Tasto per aggiungere un nuovo piatto -->
    {% if user.is_authenticated and "Chef" in user.groups.all.0.name%}
        <a class="btn btn-success d-inline" href="{% url 'menu:dish_create' %}">Aggiungi un nuovo piatto</a> <!-- Tasto per aggiungere un nuovo piatto -->
        {% endif %}
    </div>
{% endblock %}

menu/templates/menu/search_dish.html
{% extends "base.html" %}

{% block title %} Ricerca {% endblock %}

{% block content %}
    <h1>Ricerca Piatti</h1>
    <form action="{% url 'menu:dish_search' %}" method="POST"> {% csrf_token %}
    {{form.as_p}}
    <button type="submit" class="btn btn-primary">Cerca</button>
   </form>
{% endblock %}

menu/templates/menu/search_results.html
{% extends "base.html" %}

{% block title %} Risultati {% endblock %}

{% block content %}
<h2>Risultati</h2>
<ul>
    {% if object_list %}
        {% for dish in object_list %}

            <li>
                <a href="{% url 'menu:dish_detail' dish.pk %}">{{ dish.name }}</a> - {{ dish.price }}€
                <ul>
                    {% for ingredient in dish.ingredients.all %}
                        <li>{{ ingredient }}</li>
                    {% endfor %}
                </ul>
            </li>
        {% endfor %}
    {% else %}
        <p>Piatti non trovati.</p>
    {% endif %}
    
    
    <a class="btn btn-primary" href="{% url 'menu:dish_search' %}">Nuova ricerca</a>
{% endblock %}
</ul>