menu/urls.py
# menu/urls.py
from django.urls import path
from .views import *
app_name = 'menu'

urlpatterns = [
    # path per la lista dei piatti
    path('', MenuListView.as_view(), name='menu'),
    
    # path per operazioni CRUD sui piatti
    path('new_dish/', DishCreateView.as_view(), name='dish_create'),
    path('edit_dish/<pk>', DishUpdateView.as_view(), name='dish_edit'),
    path('delete_dish/<pk>', DishDeleteView.as_view(), name='dish_delete'),
    path('detail_dish/<pk>', DishDetailView.as_view(), name='dish_detail'),
    
    # path per la lista degli ingredienti
    path('ingredient_list/', IngredientListView.as_view(), name='ingredient_list'),
    
    # path per operazioni CRUD sugli ingredienti
    path('new_ingredient/', IngredientCreateView.as_view(), name='ingredient_create'),
    path('edit_ingredient/<pk>', IngredientUpdateView.as_view(), name='ingredient_edit'),
    path('delete_ingredient/<pk>', IngredientDeleteView.as_view(), name='ingredient_delete'),
    path('detail_ingredient/<pk>', IngredientDetailView.as_view(), name='ingredient_detail'),
    
    # path per eseeguire una ricerca
    path ('search/', dish_search, name='dish_search'),
    path ('search_results/', SearchResultsList.as_view(), name='search_results'),
    
    path('dish/<int:dish_id>/', dish_statistics, name='dish_statistics'),


]

orders/urls.py
from django.urls import path
from .views import *
app_name = 'orders'

urlpatterns = [
    path('current/', CurrentOrderDetailView.as_view(), name='current_order_detail'),
    path('current/<int:table_id>/', CurrentOrderDetailView.as_view(), name='current_order_detail_with_id'),
    
    path('delete_order/<int:table_id>/', CurrentOrderDeleteView.as_view(), name='current_order_delete'),
    
    path('update/<int:pk>/', OrderUpdateView.as_view(), name='order_detail_update'),
    path('delete/<int:pk>/', OrderDeleteView.as_view(), name='order_detail_delete'),
    
    path('confirm/', confirm_order_view, name='confirm_order'),
    path('conclude_evening/', conclude_evening_view, name='conclude_evening'),
    path('confirm/<int:table_id>/', confirm_order_view, name='confirm_order_with_id'),
    path('conclude_evening/<int:table_id>/', conclude_evening_view, name='conclude_evening_with_id'),

    path('update_order_detail_status/<int:order_detail_id>/', update_order_detail_status, name='update_order_detail_status'),
    
    path('recommendations/<int:pk>/', order_recommendations_view, name='order_recommendations'),

    path('statistics/', orders_statistics, name='statistics'),



]

sushi/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import *
# from .initcmds import erase_dish_db, erase_ingredient_db, init_ingredient_db, init_dish_db
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static
from orders.reccomendation import create_similarity_matrix, populate_initial_cooccurrence_matrix


urlpatterns = [
    path('', include('restaurant.urls')),  
    
    path('admin/', admin.site.urls, name='admin'),
    
    path("login/", auth_views.LoginView.as_view(), name="login"),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
    path("register/", TableCreateView.as_view(), name="register"),
    path("register_chef/",ChefCreateView.as_view(), name="register_chef"),
    
    path('menu/', include('menu.urls')),

    path('tables/', include('tables.urls')),
    
    path('orders/', include('orders.urls')),
    
]
create_similarity_matrix()
populate_initial_cooccurrence_matrix()
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tables/urls.py
# menu/urls.py
from django.urls import path
from .views import *
app_name = 'tables'

urlpatterns = [
    path('', TableListView.as_view(), name='table_list'),
    path('<int:pk>/', TableDetailView.as_view(), name='table_detail'),
    path('my_table/', user_table_redirect, name='my_table'),
    path('update/<int:pk>/', TableUpdateView.as_view(), name='table_update'),
    path('delete/<int:pk>/', TableDeleteView.as_view(), name='table_delete'),

   
]

tables/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Table(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    table_number = models.PositiveIntegerField(unique=True, error_messages={
            'unique': "Numero già esistente!!! Non è possibile avere due tavoli con lo stesso numero.",
        })
    
    def delete(self, *args, **kwargs):
        # Cancella l'utente associato prima di cancellare il tavolo
        self.user.delete()
        # Cancella il tavolo
        super().delete(*args, **kwargs)
    
    def __str__(self):
        return f'Tavolo {self.user.username} N° {self.table_number}'

tables/forms.py
from django import forms
from .models import Table
from django.core.exceptions import ValidationError
from django.core.exceptions import PermissionDenied
from django.contrib.auth.models import User

# Questa classe mixin controlla se l'utente è il proprietario del tavolo oppure se è uno chef
class UserIsTableOwnerMixin:
    def dispatch(self, request, *args, **kwargs):
        table = self.get_object()
        
        if table.user != request.user and not request.user.groups.filter(name='Chef').exists()  :
            raise PermissionDenied            
        return super().dispatch(request, *args, **kwargs)
# N.B.: Questo mixin è stato utilizzato nella vista TableDetailView, e dovrebbe essere in un file specifico detto mixins.py
# ma l'ho messo qui per comodità


class TableUpdateForm(forms.ModelForm):
    username = forms.CharField(label="Username")
    password = forms.CharField(label="Nuova Password", required=False, widget=forms.PasswordInput)
    confirm_password = forms.CharField(label="Conferma Password", required=False, widget=forms.PasswordInput)
    table_number = forms.IntegerField(label="Numero del tavolo")

    class Meta:
        model = User
        fields = ['username', 'password', 'confirm_password', 'table_number']

    def __init__(self, *args, **kwargs):
        # Recupero l'istanza del tavolo passata come argomento
        self.table_instance = kwargs.pop('table_instance')
        super().__init__(*args, **kwargs)
        # Inizializzo i campi con i valori attuali
        self.fields['username'].initial = self.table_instance.user.username
        self.fields['table_number'].initial = self.table_instance.table_number

    # Questo metodo controlla se il nome utente è già in uso
    def clean_username(self):
        username = self.cleaned_data.get('username')
        if User.objects.filter(username=username).exclude(pk=self.table_instance.user.pk).exists():
            raise ValidationError("Questo nome utente è già in uso. Scegli un altro nome utente.")
        return username

    def clean(self):
        cleaned_data = super().clean()
        # Controllo se le password corrispondono
        password = cleaned_data.get("password")
        confirm_password = cleaned_data.get("confirm_password")

        if password and password != confirm_password:
            self.add_error('confirm_password', "Le password non corrispondono.")
        return cleaned_data
    
    def save(self, commit=True):
        # ottengo l'utente daò tavolo
        user = self.table_instance.user
        # ne modifico l'username e la password
        user.username = self.cleaned_data['username']
        password = self.cleaned_data['password']
        if password:
            user.set_password(password)
        if commit:
            # salvo l'utente e il tavolo
            user.save()
            table = self.table_instance
            table.table_number = self.cleaned_data.get('table_number')
            table.save()
        
        return table

tables/views.py
from braces.views import GroupRequiredMixin
from django.views.generic.edit import UpdateView, DeleteView
from django.views.generic import ListView, DetailView
from orders.models import Order
from .models import Table
from django.contrib.auth.mixins import LoginRequiredMixin
from .forms import UserIsTableOwnerMixin, TableUpdateForm
from django.urls import reverse_lazy
from django.contrib import messages
from django.contrib.auth.decorators import user_passes_test
from django.shortcuts import get_object_or_404, redirect



class TableListView(LoginRequiredMixin, ListView):
    model = Table
    template_name = 'tables/table_list.html'
    context_object_name = 'tables'

class TableDetailView(LoginRequiredMixin, UserIsTableOwnerMixin, DetailView):
    model = Table
    template_name = 'tables/table_detail.html'
    context_object_name = 'table'

    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # recupera tutti gli ordini per il tavolo corrente
        orders = Order.objects.filter(table=self.object)
        context['orders'] = orders
        
        # controlla se ci sono ordini in sospeso per il tavolo corrente
        context['has_pending_order'] = orders.filter(status="da confermare").exists()
        
        # calcola il totale degli ordini, ma solo quelli confermati
        context['total_price'] = sum(order.total_price for order in orders.filter(status="confermato"))
        
        return context
    
class TableUpdateView(GroupRequiredMixin, UpdateView):
    group_required = ["Chef"]
    model = Table
    form_class = TableUpdateForm
    template_name = 'tables/table_update.html'
    success_url = reverse_lazy('tables:table_list')
    
    def form_valid(self, form):
        response = super().form_valid(form)
        messages.success(self.request, 'Aggiornamento del tavolo avvenuta con successo!!!')
        return response    
    
    # Questo metodo serve per passare l'istanza del tavolo al form
    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['table_instance'] = self.get_object()
        return kwargs


class TableDeleteView(GroupRequiredMixin, DeleteView):
    group_required = ["Chef"]
    model = Table
    template_name = 'tables/table_delete.html'
    success_url = reverse_lazy('tables:table_list')
    
    def post (self, request, *args, **kwargs):
        messages.success(self.request, 'Eliminazione del tavolo avvenuta con successo!!!')
        return super().post(request, *args, **kwargs)

def has_group(user):
    return user.groups.filter(name='Tavolo').exists()

@user_passes_test(has_group)  
def user_table_redirect(request):
    # Ottieni il tavolo associato all'utente loggato
    table = get_object_or_404(Table, user=request.user)
    # Reindirizza alla view del dettaglio del tavolo
    return redirect('tables:table_detail', pk=table.pk)

tables/templates/tables/table_delete.html
{% extends 'base.html' %}

{% block title %}Elimina Tavolo N°{{ table.table_number}}{% endblock %}


{% block content %}
    <h1>Elimina Tavolo</h1>
    <p>Sei sicuro di voler eliminare il tavolo {{table.user.username}}?</p>
    <form method="post">
        {% csrf_token %}
        <div class="d-flex ">
        <button type="submit" class="btn btn-danger mr-2">Elimina</button>
    </form>
    <a class="btn btn-info" href="{% url 'tables:table_detail' table.pk %}">Torna al dettaglio del tavolo</a>
    </div>
{% endblock %}

tables/templates/tables/table_detail.html
{% extends "base.html" %}
{% block title %}Tavolo {{table.user.username}}{% endblock %}

{% block content %}
{% if messages %}
    {% for message in messages %}
        <div class="alert alert-{{ message.tags }}" role="alert">
            {{ message }}
        </div>
    {% endfor %}
    
{% endif %}

<h2>Dettagli del Tavolo {{ table.table_number }}</h2>
<p>Nome Tavolo: {{ table.user.username }}</p>

<h3>Ordini</h3>
<ul>
    {% if orders %}
        {% for order in orders %}
        {% if order.status == "confermato" %}
            <li>Ordine {{ order.id }} - {{ order.order_datetime }}</li>
            <ul>
                {% for detail in order.order_details.all %}
                <li id="order-detail-{{ detail.id }}">
                    {{ detail.dish.name }} - <span class="status">{{ detail.status }}</span>
                    {% if user.is_authenticated and "Chef" in user.groups.all.0.name %}
                    <button class="btn btn-info" onclick="updateStatus({{ detail.id }})">Cambia stato</button>
                    {% endif %}
                </li>
                    {% comment %} <li>
                    {{ detail }}
                    {% if user.is_authenticated and "Chef" in user.groups.all.0.name  %}
                        <form method="post" action="{% url 'orders:update_order_detail_status' detail.id %}">
                        {% csrf_token %}
                            <button class="btn btn-info" type="submit">Cambia stato</button>
                        </form>
                    {% endif %} 
                    </li> {% endcomment %}
                   
                {% endfor %}
            </ul>
            <p>Totale Ordine: {{ order.total_price }} €</p>        
        {% else %}
            <div class="alert-warning" role="alert" style="max-width: 250px;">
                <p>C'è un ordine da confermare</p>
            </div>
            <a class="btn btn-success" href="{% url 'orders:current_order_detail_with_id' table.id %}">Ordine Corrente</a> <!-- Tasto per l'ordine corrente -->
        {% endif %}

        {% endfor %}
        <br>
        <strong>Totale complessivo: {{ total_price }} €</strong>

        {% if not has_pending_order %}
        <form method="post" action="{% url 'orders:conclude_evening_with_id' table.id %}">
            {% csrf_token %}
            <button class="btn btn-success" type="submit">Concludi Serata</button>
        </form>
        {% endif %}
    {% else %}
        <p>Questo tavolo non ha effettuato ordini.</p>
    {% endif %}
</ul>
{% if user.is_authenticated and "Chef" in user.groups.all.0.name  %}
    <a class="btn btn-success" href="{% url 'tables:table_update' table.pk %}">Modifica</a> <!-- Tasto per modificare il piatto -->
    <a class="btn btn-danger" href="{% url 'tables:table_delete' table.pk %}">Elimina</a> <!-- Tasto per eliminare il piatto -->

{% endif %}
{% block scripts %}
<script>
    function updateStatus(orderDetailId) {
        var csrfToken = '{{ csrf_token }}';
        var xhr = new XMLHttpRequest();
        xhr.open("POST", "{% url 'orders:update_order_detail_status' 0 %}".replace('0', orderDetailId), true);
        xhr.setRequestHeader("Content-Type", "application/x-www-form-urlencoded");
        xhr.setRequestHeader("X-CSRFToken", csrfToken);

        xhr.onreadystatechange = function() {
            if (xhr.readyState === XMLHttpRequest.DONE) {
                if (xhr.status === 200) {
                    var response = JSON.parse(xhr.responseText);
                    document.querySelector("#order-detail-" + orderDetailId + " .status").textContent = response.status;
                } else {
                    alert('Errore durante l\'aggiornamento dello stato.');
                }
            }
        };

        xhr.send("csrfmiddlewaretoken=" + csrfToken);
    }
</script>

{% endblock %}

{% endblock %}

tables/templates/tables/table_list.html
{% extends "base.html" %}
{% block title %}Tavoli{% endblock %}
{% block content %}
{% if messages %}
    {% for message in messages %}
        <div class="alert alert-{{ message.tags }}" role="alert">
            {{ message }}
        </div>
    {% endfor %}
{% endif %}
<h2>Lista dei Tavoli</h2>
    {% if tables %}
    <ul class="list-group list-group-flush">

        {% for table in tables %}
        <li class="list-group-item">
            <a href="{% url 'tables:table_detail' table.pk %}">{{ table }}</a>
        </li>
    </ul>
        {% endfor %}
    {% else %}
        <p>Non ci sono tavoli disponibili.</p>
    {% endif %} 
{% if user.is_authenticated and "Chef" in user.groups.all.0.name  %}
        <a class="btn btn-info" href="{% url 'orders:statistics' %}">Statistiche</a> <!-- Tasto per eliminare il piatto -->
    {% endif %}

{% endblock %}

tables/templates/tables/table_update.html
{% extends 'base.html' %}

{% block title %} Aggiornamento Tavolo  {% endblock %} 

{% block  content %}
  <h1>Pagina per modificare le informazioni del Tavolo {{table.user.username}}</h1>
  <p>Si prega di compilare i campi necessari</p> 

  <form method="post"> {% csrf_token %}

  {{form }}
  
  <button type="submit" class="btn btn-success">Aggiorna</button>
  
  </form>

{% endblock %}