menu/urls.py
# menu/urls.py
from django.urls import path
from .views import *
app_name = 'menu'

urlpatterns = [
    # path per la lista dei piatti
    path('', MenuListView.as_view(), name='menu'),
    
    # path per operazioni CRUD sui piatti
    path('new_dish/', DishCreateView.as_view(), name='dish_create'),
    path('edit_dish/<pk>', DishUpdateView.as_view(), name='dish_edit'),
    path('delete_dish/<pk>', DishDeleteView.as_view(), name='dish_delete'),
    path('detail_dish/<pk>', DishDetailView.as_view(), name='dish_detail'),
    
    # path per la lista degli ingredienti
    path('ingredient_list/', IngredientListView.as_view(), name='ingredient_list'),
    
    # path per operazioni CRUD sugli ingredienti
    path('new_ingredient/', IngredientCreateView.as_view(), name='ingredient_create'),
    path('edit_ingredient/<pk>', IngredientUpdateView.as_view(), name='ingredient_edit'),
    path('delete_ingredient/<pk>', IngredientDeleteView.as_view(), name='ingredient_delete'),
    path('detail_ingredient/<pk>', IngredientDetailView.as_view(), name='ingredient_detail'),
    
    # path per eseeguire una ricerca
    path ('search/', dish_search, name='dish_search'),
    path ('search_results/', SearchResultsList.as_view(), name='search_results'),
    
    path('dish/<int:dish_id>/', dish_statistics, name='dish_statistics'),


]

orders/urls.py
from django.urls import path
from .views import *
app_name = 'orders'

urlpatterns = [
    path('current/', CurrentOrderDetailView.as_view(), name='current_order_detail'),
    path('current/<int:table_id>/', CurrentOrderDetailView.as_view(), name='current_order_detail_with_id'),
    
    path('delete_order/<int:table_id>/', CurrentOrderDeleteView.as_view(), name='current_order_delete'),
    
    path('update/<int:pk>/', OrderUpdateView.as_view(), name='order_detail_update'),
    path('delete/<int:pk>/', OrderDeleteView.as_view(), name='order_detail_delete'),
    
    path('confirm/', confirm_order_view, name='confirm_order'),
    path('conclude_evening/', conclude_evening_view, name='conclude_evening'),
    path('confirm/<int:table_id>/', confirm_order_view, name='confirm_order_with_id'),
    path('conclude_evening/<int:table_id>/', conclude_evening_view, name='conclude_evening_with_id'),

    path('update_order_detail_status/<int:order_detail_id>/', update_order_detail_status, name='update_order_detail_status'),
    
    path('recommendations/<int:pk>/', order_recommendations_view, name='order_recommendations'),

    path('statistics/', orders_statistics, name='statistics'),



]

restaurant/urls.py
from django.urls import path,re_path
from .views import *
app_name = 'restaurant'
urlpatterns = [
    re_path(r"^$|^/$|^home/$", homepage, name="homepage"),
    path('about/', about_us, name='about_us'),
    path('edit_restaurant_info/', edit_restaurant_info, name='edit_restaurant_info'),
    path('edit_contact_info/', edit_about_us, name='edit_contact_info'),
]

sushi/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import *
# from .initcmds import erase_dish_db, erase_ingredient_db, init_ingredient_db, init_dish_db
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static
from orders.reccomendation import create_similarity_matrix, populate_initial_cooccurrence_matrix


urlpatterns = [
    path('', include('restaurant.urls')),  
    
    path('admin/', admin.site.urls, name='admin'),
    
    path("login/", auth_views.LoginView.as_view(), name="login"),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
    path("register/", TableCreateView.as_view(), name="register"),
    path("register_chef/",ChefCreateView.as_view(), name="register_chef"),
    
    path('menu/', include('menu.urls')),

    path('tables/', include('tables.urls')),
    
    path('orders/', include('orders.urls')),
    
]
create_similarity_matrix()
populate_initial_cooccurrence_matrix()
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tables/urls.py
# menu/urls.py
from django.urls import path
from .views import *
app_name = 'tables'

urlpatterns = [
    path('', TableListView.as_view(), name='table_list'),
    path('<int:pk>/', TableDetailView.as_view(), name='table_detail'),
    path('my_table/', user_table_redirect, name='my_table'),
    path('update/<int:pk>/', TableUpdateView.as_view(), name='table_update'),
    path('delete/<int:pk>/', TableDeleteView.as_view(), name='table_delete'),

   
]

templates/base.html
<!DOCTYPE html>
<html lang="it">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
    {% block head %} {% endblock %}
    <title>{% block title %}{{restaurant_info.name}}{% endblock %}</title>
</head>
<body>
    <nav class="navbar navbar-expand-lg" style="background-color: #e3f2fd;">
        <div class="container-fluid">
            <a class="navbar-brand" href="{% url 'restaurant:homepage' %}">Home</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'restaurant:about_us' %}">Chi Siamo</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'menu:menu' %}">Menu</a>
                </li>
                {% if user.is_authenticated %}
                    {% if "Tavolo" in user.groups.all.0.name %}
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page"  href="{% url 'orders:current_order_detail' %}">Ordine Corrente</a> <!-- Tasto per l'ordine corrente -->
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'tables:my_table' %}">Il Mio Tavolo</a>
                    </li>
                    {% endif %}
                    {%if "Chef" in user.groups.all.0.name %} 
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'tables:table_list' %}">Lista Tavoli</a> <!-- Tasto per la lista di tavoli -->
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'menu:ingredient_list' %}">Lista Ingredienti</a> <!-- Tasto per la lista di ingredienti -->
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'register' %}">Registrazione Tavolo</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'restaurant:edit_restaurant_info'%}">Modifica homepage</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'restaurant:edit_contact_info'%}">Modifica About Us</a>      
                    </li>
                    {% endif %}  
                    {% if user.is_staff %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'register_chef' %}">Registrazione Chef</a></li>
                    </li>
                    {% endif %} 
                    <li class="nav-item">
                        <form method="POST" action="{% url 'logout' %}">
                            {% csrf_token %}
                        <button type="submit" class="btn btn-link">Logout</button>
                        </form>
                    </li>
                {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'login' %}">Login</a></li>
                </li>
                <li class="nav-item">
                    <a class="nav-link"  href="/admin/" >Admin Login</a>
                </li>
                {% endif %}
                </ul>
              </div>
            </div>
          </nav>
    <div class="ml-2">
        {% block content %} {% endblock %}
    </div>
        <div class="card mt-4">
            <div class="card-header">
              Buon appetito.
            </div>
            <div class="card-body">
              <blockquote class="blockquote mb-0">
                <p>&copy; Dal 2002, portiamo avanti la nostra passione per il sushi e l'eccellenza culinaria</p>
                <footer class="blockquote-footer">Sughi Shapi <cite title="Source Title"></cite></footer>
              </blockquote>
            </div>
          </div>
</body>
</html>

templates/user_create.html
{% extends 'base.html' %}

{% block title %} Creazione {{ form.user_group_name }} {% endblock %} 

{% block  content %}
  <h1>Pagina di Registrazione di un tavolo</h1>
  <p>Si prega di compilare i campi necessari</p> 

  <form method="post"> {% csrf_token %}

  {{form }}
  
  <input type="submit" value="Registrati ora!">
  
  </form>

{% endblock %}